### ISSUE TITLE
Define front-end technology

### ISSUE THREAD

**Issue by vanhacktech** [vanhack-technologies-inc/ats#2]
What kind of technology should we use for the front-end of this project?

**Comment by jcserracampos** [comment]
First we need to decide if we will use microservices or build a monolith project.
If we choose to separate back-end and back-end projects, we can use ReactJS, Angular, VueJs and EmberJs. Anything beside this can bring problems because of lack of programmers.

**Comment by farhantahir** [comment]
Separate Front-End and Separate Back-End is better than having all in one place. Because it increases overall size of the code base and makes it difficult to manage and maintain later on.

**Comment by farhantahir** [comment]
I think React with Redux and redux-saga with materialize-css.

**Comment by asifsha** [comment]
React & React Native

**Comment by tiagozaccaro** [comment]
I have experience with angular 5 and I like it a lot.

**Comment by farhantahir** [comment]
@asifsha  React Native is good addition as well.

**Comment by jcserracampos** [comment]
I know that last VanHackaton had React positions.
Another approach is to use micro-frontends so we can use more than one technology.

**Comment by VijayVardhan23** [comment]
React and redux with bootstrap

**Comment by thedma04** [comment]
I think we first need to come out with the various user stories that the app will need. After classifying the various needs we could now have a base to choose the technology that best fits the solution we are building

**Comment by farhantahir** [comment]
@thedma04 A valid point.

**Comment by jcserracampos** [comment]
Only React was suggested, so I think we can use React.

**Comment by Macrichie** [comment]
Yes we should use React as the entire frontend of Vanhack platform was written in React.

**Comment by vanhacktech** [comment]
Ok we have a decision about the front end technology, we are going to use React!
